-- Neptune Schema Migration
-- 1. Drop Groups table and remove Group ID from Athletes
-- 2. Add Team (org name) to profiles
-- 3. Create Trainings table
-- 4. Create Exercises table

-- ============================================================
-- Step 1: Remove Group references
-- ============================================================

-- Drop the FK column from Athletes
ALTER TABLE "Athletes" DROP COLUMN IF EXISTS "Group ID";

-- Drop the Groups table
DROP TABLE IF EXISTS "Groups";

-- ============================================================
-- Step 2: Add organization name to profiles
-- ============================================================

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS "Team" text;

-- ============================================================
-- Step 3: Create Trainings table
-- ============================================================

CREATE TABLE IF NOT EXISTS "Trainings" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  "Name" text,
  "Notes" text,
  "Team" bigint REFERENCES "Teams"(id),
  "Date" date,
  "Days" json,
  "User ID" uuid DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE "Trainings" ENABLE ROW LEVEL SECURITY;

-- Users can only see their own trainings
CREATE POLICY "Users can view own trainings"
  ON "Trainings" FOR SELECT
  USING (auth.uid() = "User ID");

CREATE POLICY "Users can insert own trainings"
  ON "Trainings" FOR INSERT
  WITH CHECK (auth.uid() = "User ID");

CREATE POLICY "Users can update own trainings"
  ON "Trainings" FOR UPDATE
  USING (auth.uid() = "User ID");

CREATE POLICY "Users can delete own trainings"
  ON "Trainings" FOR DELETE
  USING (auth.uid() = "User ID");

-- ============================================================
-- Step 4: Create Exercises table
-- ============================================================

CREATE TABLE IF NOT EXISTS "Exercises" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  "Training ID" bigint NOT NULL REFERENCES "Trainings"(id) ON DELETE CASCADE,
  "Name" text,
  "Distance" bigint,
  "Repetitions" bigint,
  "Energy System" text,
  "Interval" bigint,
  "Note" text,
  "User ID" uuid DEFAULT auth.uid()
);

-- Enable RLS
ALTER TABLE "Exercises" ENABLE ROW LEVEL SECURITY;

-- Users can only see their own exercises
CREATE POLICY "Users can view own exercises"
  ON "Exercises" FOR SELECT
  USING (auth.uid() = "User ID");

CREATE POLICY "Users can insert own exercises"
  ON "Exercises" FOR INSERT
  WITH CHECK (auth.uid() = "User ID");

CREATE POLICY "Users can update own exercises"
  ON "Exercises" FOR UPDATE
  USING (auth.uid() = "User ID");

CREATE POLICY "Users can delete own exercises"
  ON "Exercises" FOR DELETE
  USING (auth.uid() = "User ID");
